import { faker } from '@faker-js/faker';
import {
  AmountType,
  AudienceType,
  LanguageType,
  Prisma,
  PrismaClient,
  RoleType,
  ScenarioType,
  ScopeType,
  SourceType,
  StatusType,
  ThemeType,
  ToneType,
  VisibilityType,
} from '@prisma/client';

const getRandomEnumValue = <T extends Record<string, unknown>>(
  anEnum: T,
): T[keyof T] => {
  const enumValues = Object.values(anEnum) as T[keyof T][];
  return faker.helpers.arrayElement(enumValues);
};

// --- Mock Data Generators for Complex JSON Fields ---

const createMockOutlines = (): Outlines => {
  return [
    {
      id: faker.string.uuid(),
      order: '1',
      title: 'Introduction to Our Topic',
      subtitle: 'A brief overview',
      description: 'Defining the core concepts and goals.',
      representation: 'TITLE_CARD',
      concepts: ['introduction', 'overview', 'goals', faker.lorem.word()],
    },
    {
      id: faker.string.uuid(),
      order: '2',
      title: 'Deep Dive into Section 2',
      subtitle: 'Exploring the details',
      description: 'A detailed breakdown of the second section.',
      representation: 'BULLETS',
      concepts: ['details', 'analysis', 'section-2', faker.lorem.word()],
    },
  ];
};

const createMockAiMetadata = (): AiMetadata => {
  return {
    mastra: {
      agentId: faker.string.uuid(),
      traceId: faker.string.uuid(),
      version: '1.0.0',
      duration: faker.number.int({ min: 1000, max: 5000 }),
      steps: [
        {
          name: 'initial_generation',
          tool: 'gemini_flash_api',
          duration: faker.number.int({ min: 100, max: 500 }),
          status: 'success',
          usage: {
            promptTokens: faker.number.int({ min: 50, max: 200 }),
            completionTokens: faker.number.int({ min: 100, max: 400 }),
            totalTokens: faker.number.int({ min: 150, max: 600 }),
          },
          result: { success: true },
        },
      ],
    },
    usage: {
      promptTokens: faker.number.int({ min: 100, max: 500 }),
      completionTokens: faker.number.int({ min: 200, max: 1000 }),
      totalTokens: faker.number.int({ min: 300, max: 1500 }),
      cost: faker.number.float({ min: 0.01, max: 0.1 }),
      currency: 'USD',
    },
    model: {
      name: 'gemini-1.5-pro',
      provider: 'google',
    },
    context: {
      outlineSlidesCount: 2,
      documentId: faker.string.uuid(),
    },
  };
};

const createMockSlides = (): Slides => {
  const mockOutline: Outline = {
    id: faker.string.uuid(),
    order: '1',
    title: 'A Mock Slide',
    subtitle: 'From the factory',
    description: 'This is a mock slide generated by the factory.',
    representation: 'BULLETS',
    concepts: ['mock', 'factory', 'slide', faker.lorem.word()],
  };
  const mockScene: ExcalidrawScene = {
    type: 'excalidraw',
    version: 2,
    source: 'presenterai',
    elements: [],
    appState: {
      gridSize: null,
      viewBackgroundColor: '#FFFFFF',
    } as any,
    files: {},
  };

  return [
    {
      id: faker.string.uuid(),
      order: '1',
      outline: mockOutline,
      scene: mockScene,
    },
  ];
};

// --- Model Factories ---

export const userFactory = async (
  prisma: PrismaClient,
  data?: Partial<Prisma.UserCreateInput>,
) => {
  const defaults: Prisma.UserCreateInput = {
    name: faker.person.fullName(),
    email: faker.internet.email(),
    emailVerified: true,
    image: faker.image.avatar(),
    role: getRandomEnumValue(RoleType),
    status: getRandomEnumValue(StatusType),
  };
  return prisma.user.create({ data: { ...defaults, ...data } });
};

export const documentFactory = async (
  prisma: PrismaClient,
  data: Partial<Prisma.DocumentCreateInput> & {
    user: { connect: { id: string } };
  },
) => {
  const defaults: Omit<Prisma.DocumentCreateInput, 'user'> = {
    name: faker.lorem.words({ min: 3, max: 8 }),
    visibility: getRandomEnumValue(VisibilityType),
    status: getRandomEnumValue(StatusType),
  };
  return prisma.document.create({ data: { ...defaults, ...data } });
};

export const generationFactory = async (
  prisma: PrismaClient,
  data: Partial<Prisma.GenerationCreateInput> & {
    document: { connect: { id: string } };
    user: { connect: { id: string } };
  },
) => {
  const defaults: Omit<Prisma.GenerationCreateInput, 'document' | 'user'> = {
    source: getRandomEnumValue(SourceType),
    scope: getRandomEnumValue(ScopeType),
    tone: getRandomEnumValue(ToneType),
    amount: getRandomEnumValue(AmountType),
    audience: getRandomEnumValue(AudienceType),
    scenario: getRandomEnumValue(ScenarioType),
    theme: getRandomEnumValue(ThemeType),
    language: getRandomEnumValue(LanguageType),
    quantity: faker.number.int({ min: 1, max: 10 }),
    aspectRatio: '16_9',
    keywords: [faker.lorem.word(), faker.lorem.word()],
    prompt: faker.lorem.paragraph(),
    outlines: createMockOutlines() as Prisma.InputJsonValue,
    aiMetadata: createMockAiMetadata() as Prisma.InputJsonValue,
    status: getRandomEnumValue(StatusType),
  };
  return prisma.generation.create({ data: { ...defaults, ...data } });
};

export const presentationFactory = async (
  prisma: PrismaClient,
  data: Partial<Prisma.PresentationCreateInput> & {
    user: { connect: { id: string } };
    generation: { connect: { id: string } };
  },
) => {
  const defaults: Omit<
    Prisma.PresentationCreateInput,
    'user' | 'generation'
  > = {
    slug: faker.lorem.slug(),
    source: getRandomEnumValue(SourceType),
    slides: createMockSlides() as Prisma.InputJsonValue,
    aiMetadata: createMockAiMetadata() as Prisma.InputJsonValue,
    status: getRandomEnumValue(StatusType),
  };
  return prisma.presentation.create({ data: { ...defaults, ...data } });
};

export const accountFactory = async (
  prisma: PrismaClient,
  data: Partial<Prisma.AccountCreateInput> & {
    user: { connect: { id: string } };
  },
) => {
  const defaults: Omit<Prisma.AccountCreateInput, 'user'> = {
    provider: 'credential',
    providerAccountId: data.user.connect.id,
    accountId: data.user.connect.id,
    providerId: 'credential',
    password: '12345678', 
  };
  return prisma.account.create({ data: { ...defaults, ...data } });
};