export const APP_ROUTES = {
  HOME: {
    path: "/",
    label: "Home",
    icon: "Home",
    authRequired: false,
  },

  AUTH: {
    SIGN_IN: {
      path: "/auth/sign-in",
      label: "Sign In",
      icon: "LogIn",
      authRequired: false,
    },
    SIGN_UP: {
      path: "/auth/sign-up",
      label: "Sign Up",
      icon: "UserPlus",
      authRequired: false,
    },
    FORGOT_PASSWORD: {
      path: "/auth/forgot-password",
      label: "Forgot Password",
      icon: "Lock",
      authRequired: false,
    },
    RESET_PASSWORD: {
      path: "/auth/reset-password",
      label: "Reset Password",
      icon: "Unlock",
      authRequired: false,
    },
  },

  APP: {
    path: "/app",
    authRequired: true,
    roles: ["MEMBER"],
    requireEmailVerified: true,
    redirects: {
      unauthenticated: "/auth/sign-in",
      unauthorized: "/",
      emailNotVerified: "/",
    },
    APP: {
      path: "/app",
      label: "Dashboard",
      icon: "Gauge",
      authRequired: true,
      roles: ["MEMBER"],
    },
    GENERATE: {
      NEW: "/app/generate",
      DETAIL: (id: string | number) => `/app/generate/${id}`,
      label: "Generate",
      icon: "MagicWand",
      authRequired: true,
      roles: ["MEMBER"],
    },
    PRESENTATIONS: {
      LIST: "/app/presentations",
      DETAIL: (id: string | number) => `/app/presentations/${id}`,
      label: "Presentations",
      icon: "Presentation",
      authRequired: true,
      roles: ["MEMBER"],
    },
    DOCUMENTS: {
      LIST: "/app/documents",
      DETAIL: (id: string | number) => `/app/documents/${id}`,
      label: "My Documents",
      icon: "FileText",
      authRequired: true,
      roles: ["MEMBER"],
    },
  },
  ADMIN: {
    path: "/admin",
    authRequired: true,
    roles: ["ADMIN"],
    requireEmailVerified: true,
    redirects: {
      unauthenticated: "/auth/sign-in",
      unauthorized: "/app",
      emailNotVerified: "/",
    },
    DASHBOARD: {
      path: "/admin/dashboard",
      label: "Dashboard",
      icon: "LayoutDashboard",
      authRequired: true,
      roles: ["ADMIN"],
    },
    USERS: {
      LIST: "/admin/users",
      DETAIL: (id: string | number) => `/admin/users/${id}`,
      NEW: "/admin/users/new",
      EDIT: (id: string | number) => `/admin/users/${id}/edit`,
      label: "Users",
      icon: "Users",
      authRequired: true,
      roles: ["ADMIN"],
    },
    DOCUMENTS: {
      LIST: "/admin/documents",
      DETAIL: (id: string | number) => `/admin/documents/${id}`,
      NEW: "/admin/documents/new",
      EDIT: (id: string | number) => `/admin/documents/${id}/edit`,
      label: "Documents",
      icon: "Folder",
      authRequired: true,
      roles: ["ADMIN"],
    },
    GENERATIONS: {
      LIST: "/admin/generations",
      DETAIL: (id: string | number) => `/admin/generations/${id}`,
      NEW: "/admin/generations/new",
      EDIT: (id: string | number) => `/admin/generations/${id}/edit`,
      label: "Generations",
      icon: "Sparkles",
      authRequired: true,
      roles: ["ADMIN"],
    },
    PRESENTATIONS: {
      LIST: "/admin/presentations",
      DETAIL: (id: string | number) => `/admin/presentations/${id}`,
      NEW: "/admin/presentations/new",
      EDIT: (id: string | number) => `/admin/presentations/${id}/edit`,
      label: "Presentations",
      icon: "Presentation",
      authRequired: true,
      roles: ["ADMIN"],
    },
  },

  DOCS: {
    path: "/docs",
    label: "Documentation",
    icon: "Book",
    authRequired: false,
    DETAIL: (id: string | number) => `/docs/${id}`,
  },

  TERMS: {
    path: "/terms",
    label: "Terms & Privacy",
    icon: "ScrollText",
    authRequired: false,
    DETAIL: (id: string | number) => `/legal/${id}`,
  },

  API: {
    ADMIN: {
      path: "/api/v1/admin",
      authRequired: true,
      roles: ["ADMIN"],
      redirects: {
        unauthenticated: "",
        unauthorized: "",
      },
    },
    APP: {
      path: "/api/v1/app",
      authRequired: true,
      roles: ["MEMBER"],
      redirects: {
        unauthenticated: "",
        unauthorized: "",
      },
    },
  },
};
