@hostname = http://localhost:3000/api/v1

### Create a new document and initial generation
POST {{hostname}}/documents
Content-Type: application/json

{
  "prompt": "A presentation about the benefits of using a well-structured API.",
  "scope": "MULTI_PAGE",
  "slideCount": [5],
  "language": "en-US",
  "ratio": "16:9",
  "keywords": ["api", "development", "documentation"]
}
